/**
 * Placeholder Database type. T0.3 (schema migration) replaces this file
 * with one generated by `supabase gen types typescript --linked`.
 *
 * Until then, the empty `public.Tables` schema lets the typed clients
 * compile; any callsite that tries to query a table will error at the
 * type level — surfacing the dependency on T0.3 explicitly.
 */
export type Database = {
  public: {
    Tables: Record<never, never>;
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};
